# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSEQUOIA2DockWidget
                                 A QGIS plugin
 simplifions le qutodien des forestiers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-07
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Alexandre Le Bars - SequoiAPP
        email                : alexlb329@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.PyQt.QtWidgets import QFileDialog
from qgis.PyQt.QtWidgets import QTreeWidgetItem
from PyQt5.QtGui import QIcon

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'QSEQUOIA2_dockwidget_base.ui'))


class QSEQUOIA2DockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(QSEQUOIA2DockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.populate_functions_tree()

        # chemin vers ton logo
        plugin_dir = os.path.dirname(__file__)
        logo_path = os.path.join(plugin_dir, "icon.png")

        # définit l’icône du dockwidget
        self.setWindowIcon(QIcon(logo_path))




    def populate_functions_tree(self):
        tree = self.functionsLibrary
        tree.clear()

        # =========================
        # Traitements bureautique
        # =========================
        bureautique = QTreeWidgetItem(tree)
        bureautique.setText(0, "Traitements bureautique")

        item = QTreeWidgetItem(bureautique)
        item.setText(0, "📝 Création dossier SIG")
        item.setToolTip(0, "Mise en forme du fichier excel issue du traitement UA vers SSPF")

        # =========================
        # Création cartographique
        # =========================
        carto = QTreeWidgetItem(tree)
        carto.setText(0, "Création cartographique")

        data = [
            ("🌳Create Qfield project from PARCA or UA",
             "Crée un projet Qfield depuis le projet et la base de donnée"),
            ("🔧Classification des relevées",
             "Classe les relevées selon des paramètres définis"),
            ("🖥Qfield vers excel et UA",
             "Mise au propre des relevés réalisé sur le terrain vers un excel et un UA complet"),
            ("📑Classer les ame_type",
             "Sort un excel de stat de la couche"),
            ("🎄Ajouter la régé",
             "Ajoute la régé depuis la couche terrain_point"),
            ("0️⃣ Retirer les 0",
             "retire les 0 de sortie sur la couche SSPF et PARFOR"),
            ("🆗Remplacer le nom des champs",
             "Remplace le nom d'un champ"),
            ("📏symbologie finale",
             "ajoute les couches TSE_point, STR_point avec le style"),
        ]

        for label, tooltip in data:
            item = QTreeWidgetItem(carto)
            item.setText(0, label)
            item.setToolTip(0, tooltip)

        # =========================
        # Cartographie environnementale
        # =========================
        envi = QTreeWidgetItem(tree)
        envi.setText(0, "Cartographie environnementale")

        ua_vecteur = QTreeWidgetItem(envi)
        ua_vecteur.setText(0, "UA vers fond vecteur")

        data = [
            ("✒️Create_COM_line", "Génération des limites de communes"),
            ("📍Create_TOPONY_point", "Intégre le nom des lieux-dits, communes et lieux d'intérets"),
            ("🚘Create_ROAD_line",
             "Création de la couche ROAD_line, avec le nom des routes et leurs classifications. source : BDTOPO IGN"),
            ("🚘Create_HYDRO",
             "création des couches Hydrologie contenant les plans d'eaux et rivières"),
            ("🏫Create_URBAIN",
             "Ajoute les couches batis, cimetières et aerodrome"),
            ("🌲 🌳Create_VEGE",
             "Intégration de la végétation et des peuplements alentours"),
            ("🗺Create_TOT_ENVI",
             "Permet en un appel d'éxécuter l'ensemble des fonctions ci dessus"),
        ]

        for label, tooltip in data:
            item = QTreeWidgetItem(ua_vecteur)
            item.setText(0, label)
            item.setToolTip(0, tooltip)

        item = QTreeWidgetItem(envi)
        item.setText(0, "🌿UA vers BDFORET")
        item.setToolTip(0, "Ajoute la BD foret la plus récente pour l'emprise de l'UA")

        # =========================
        # Traitements cartographiques
        # =========================
        traitement = QTreeWidgetItem(tree)
        traitement.setText(0, "Traitements cartographiques")

        item = QTreeWidgetItem(traitement)
        item.setText(0, "🧳Reprojection d'un vecteur")
        item.setToolTip(0, "Reprojection d'un vecteur selon un autre CRS")

        item = QTreeWidgetItem(traitement)
        item.setText(0, "📥Data IGN")
        item.setToolTip(0, "Téléchargement des bases de données de l'IGN")

        tree.expandAll()


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
