# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSEQUOIA2DockWidget
                                 A QGIS plugin
 simplifions le qutodien des forestiers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-07
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Alexandre Le Bars - SequoiAPP
        email                : alexlb329@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.PyQt.QtWidgets import QFileDialog
from qgis.PyQt.QtWidgets import QTreeWidgetItem
from PyQt5.QtGui import QIcon

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'QSEQUOIA2_dockwidget_base.ui'))


class QSEQUOIA2DockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(QSEQUOIA2DockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.populate_functions_tree()

        # chemin vers ton logo
        plugin_dir = os.path.dirname(__file__)
        logo_path = os.path.join(plugin_dir, "icon.png")

        # définit l’icône du dockwidget
        self.setWindowIcon(QIcon(logo_path))




    def populate_functions_tree(self):
        tree = self.functionsLibrary
        tree.clear()

        # =========================
        # Traitements bureautique
        # =========================
        bureautique = QTreeWidgetItem(tree)
        bureautique.setText(0, "Gestion de projets")

        data = [
            ("📝 Création dossier SIG",
             "Mise en forme du fichier excel issue du traitement UA vers SSPF"),
            ("✒️ Rangement final des couches",
             "Exporte les couches du projet courant en gpkg avec leurs styles")


        ]
        
        for label, tooltip in data:
            item = QTreeWidgetItem(bureautique)
            item.setText(0, label)
            item.setToolTip(0, tooltip)

        # =========================
        # Création cartographique
        # =========================
        utils = QTreeWidgetItem(tree)
        utils.setText(0, "Utilitaire python")

        data = [
            ("🌳Create Qfield project from PARCA or UA",
             "Crée un projet Qfield depuis le projet"),

            ("🔧Classification des relevées",
             "Classe les relevées selon des paramètres définis"),

            ("🖥Qfield vers excel et UA",
             "Mise au propre des relevés réalisé sur le terrain vers un excel et un UA complet"),

            ("📑Classer les ame_type",
             "Sort un excel de stat de la couche"),

            ("🎄Ajouter la régé",
             "Ajoute la régé depuis la couche terrain_point"),

            ("0️⃣ Retirer les 0",
             "retire les 0 de sortie sur la couche SSPF et PARFOR"),

            ("🆗Remplacer le nom des champs",
             "Remplace le nom d'un champ"),

            ("📏symbologie finale",
             "ajoute les couches TSE_point, STR_point avec le style"),

            ("📥Data IGN",
             "Téléchargement de données IGN"),

            ("🧳Reprojection d'un vecteur",
             "Reprojection d'un vecteur selon un autre CRS"),

            ("📏Détéction de la hauteur dominante",
             "dans une couche, à partir d'un LIDAR, détéction des hauteurs dominantes depuis un MNH")
            

        ]

        for label, tooltip in data:
            item = QTreeWidgetItem(utils)
            item.setText(0, label)
            item.setToolTip(0, tooltip)

        # =========================
        # Outils généraux
        # =========================

        net = QTreeWidgetItem(tree)
        net.setText(0, "Outils en ligne")

        data = [
            ("🔧Kartenn-IA",
             "Page de l'IA forestière Kartenn"),
        
            ("🔧Carto-futaie", 
             "Page de Carto-Futaie"),

            ("🔧SequoiAPP",
             "Ouvre la page internet de SequoiAPP")
        ]

        for label, tooltip in data:
            item = QTreeWidgetItem(net)
            item.setText(0, label)
            item.setToolTip(0, tooltip)



        tree.expandAll()


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
