# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forest_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets, uic

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'forest_settings.ui'))


class Ui_ForestSettingsDialog(FORM_CLASS):
    def setupUi(self, ForestSettingsDialog):
        super().setupUi(ForestSettingsDialog)
        ForestSettingsDialog.setObjectName("ForestSettingsDialog")
        ForestSettingsDialog.setEnabled(True)
        ForestSettingsDialog.setStyleSheet("") 
        ForestSettingsDialog.resize(535, 351)

