# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OSGeo4W\apps\qgis-ltr\python\plugins\Qsequoia2\dialogs\project_settings\project_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from qgis.PyQt.QtWidgets import QDoubleSpinBox
from qgis.PyQt.QtWidgets import QTreeWidgetItem

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'tools_settings.ui'))



class Ui_ToolsSettingsDialog(FORM_CLASS):
    def setupUi(self, ToolsSettingsDialog):
        super().setupUi(ToolsSettingsDialog)
        ToolsSettingsDialog.setObjectName("ToolsSettingsDialog")
        ToolsSettingsDialog.setEnabled(True)
        ToolsSettingsDialog.resize(395, 150)
 
        self.retranslateUi(ToolsSettingsDialog)
        self.populate_functions_tree()





    def retranslateUi(self, ToolsSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        ToolsSettingsDialog.setWindowTitle(_translate("ToolsSettingsDialog", "Outils python"))

    
    def populate_functions_tree(self):
        tree = self.functionsLibrary
        tree.clear()

        # nom des collones
        tree.setColumnCount(1)
        tree.setHeaderLabels(["Outils"])

        # =========================
        # Traitements bureautique
        # =========================
        bureautique = QTreeWidgetItem(tree)
        
        bureautique.setText(0, "Gestion de projets")

        data = [
            ("📝 Création dossier SIG",
             "Mise en forme du fichier excel issue du traitement UA vers SSPF"),
            ("✒️ Rangement final des couches",
             "Exporte les couches du projet courant en gpkg avec leurs styles")


        ]
        
        for label, tooltip in data:
            item = QTreeWidgetItem(bureautique)
            item.setText(0, label)
            item.setToolTip(0, tooltip)

        # =========================
        # Création cartographique
        # =========================
        utils = QTreeWidgetItem(tree)
        utils.setText(0, "Utilitaire python")

        data = [
            ("🌳Create Qfield project from PARCA or UA",
             "Crée un projet Qfield depuis le projet"),

            ("🔧Classification des relevées",
             "Classe les relevées selon des paramètres définis"),

            ("🖥Qfield vers excel et UA",
             "Mise au propre des relevés réalisé sur le terrain vers un excel et un UA complet"),

            ("📑Classer les ame_type",
             "Sort un excel de stat de la couche"),

            ("🎄Ajouter la régé",
             "Ajoute la régé depuis la couche terrain_point"),

            ("0️⃣ Retirer les 0",
             "retire les 0 de sortie sur la couche SSPF et PARFOR"),

            ("🆗Remplacer le nom des champs",
             "Remplace le nom d'un champ"),

            ("📏symbologie finale",
             "ajoute les couches TSE_point, STR_point avec le style"),

            ("📥Data IGN",
             "Téléchargement de données IGN"),

            ("🧳Reprojection d'un vecteur",
             "Reprojection d'un vecteur selon un autre CRS"),

            ("📏Détéction de la hauteur dominante",
             "dans une couche, à partir d'un LIDAR, détéction des hauteurs dominantes depuis un MNH")
            

        ]

        for label, tooltip in data:
            item = QTreeWidgetItem(utils)
            item.setText(0, label)
            item.setToolTip(0, tooltip)

        # =========================
        # Outils généraux
        # =========================

        net = QTreeWidgetItem(tree)
        net.setText(0, "Outils en ligne")

        data = [
            ("🔧Kartenn-IA",
             "Page de l'IA forestière Kartenn"),
        
            ("🔧Carto-futaie", 
             "Page de Carto-Futaie"),

            ("🔧SequoiAPP",
             "Ouvre la page internet de SequoiAPP")
        ]

        for label, tooltip in data:
            item = QTreeWidgetItem(net)
            item.setText(0, label)
            item.setToolTip(0, tooltip)



        tree.expandAll()