# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OSGeo4W\apps\qgis-ltr\python\plugins\Qsequoia2\dialogs\project_settings\project_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from qgis.PyQt.QtWidgets import QDoubleSpinBox
from qgis.PyQt.QtWidgets import QTreeWidgetItem

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'tools_settings.ui'))



class Ui_ToolsSettingsDialog(FORM_CLASS):
    def setupUi(self, ToolsSettingsDialog):
        super().setupUi(ToolsSettingsDialog)
        ToolsSettingsDialog.setObjectName("ToolsSettingsDialog")
        ToolsSettingsDialog.setEnabled(True)
        ToolsSettingsDialog.resize(395, 150)

        self.retranslateUi(ToolsSettingsDialog)






    def retranslateUi(self, ToolsSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        ToolsSettingsDialog.setWindowTitle(_translate("ToolsSettingsDialog", "Outils python"))
