assemblage:
  canvas:
    scale: 7500
    zoom_on: parca_polygon_lgd_assemblage
    readonly: [parca_polygon_lgd_assemblage]
    groups:
      - name: LEGEND
        type: vector
        layers: [parca_polygon_lgd_assemblage]
      - name: VECTEUR
        type: vector
        layers: &assemblage_w_vect 
          - com_line
          - com_point
          - infra_point_assemblage
          - infra_line
          - infra_polygon
          - lieudit_point
          - road_line
          - road_polygon
          - route_line
          - route_polygon
      - name: SEQUOIA
        type: vector
        layers: &assemblage_w_seq
          - prop_line
          - parca_polygon_occup
          - ua_polygon_occup
      - name: WMTS
        type: wmts
        layers: &assemblage_w_wmts
          - wmts_scan25_grey
          - wmts_scan100
          - wmts_scan1000
          - wmts_pci
          - wmts_irc
          - wmts_rgb
    themes:
      - name: 1_VECTEUR+SEQUOIA
        show: [*assemblage_w_vect, *assemblage_w_seq]
      - name: 2_VECTEUR+SEQUOIA+WMTS
        show: [*assemblage_w_vect, *assemblage_w_seq, *assemblage_w_wmts]
      - name: 3_SEQUOIA+WMTS
        show: [*assemblage_w_vect, *assemblage_w_wmts]
  
  layout:
    theme: '1_VECTEUR+SEQUOIA'
    legends:
      - name: legend1
        layers: ['parca_polygon_lgd_assemblage']
      - name: legend2
        layers: ['parca_polygon_occup', 'ua_polygon_occup']

situation:
  canvas:
    scale: 25000
    zoom_on: 'parca_polygon_lgd_situation'
    readonly: [parca_polygon_lgd_situation]
    groups: 
      - name: LEGEND
        type: vector
        layers: ['parca_polygon_lgd_situation']
      - name: VECTEUR
        type: vector
        layers: ['coms_point', 'coms_line', 'infra_point_situation']
      - name: SEQUOIA
        type: vector
        layers: ['prop_point', 'prop_line', 'ua_polygon_occup']
      - name: WMTS
        type: wmts
        layers: ['wmts_scan25', 'wmts_scan1000']

    themes:
      - name: 1_SCAN25
        show: ['ua_polygon_occup', 'prop_line', 'infra_point_situation', 'coms_point', 'coms_line', 'wmts_scan25']
      - name: 2_SCAN1000
        show: ['prop_point', 'wmts_scan1000']

  layout:
    theme: '1_SCAN25'
    legends:
      - name: legend1
        layers: ['parca_polygon_lgd_situation']
      - name: legend2
        layers: ['ua_polygon_occup']

peuplements:
  canvas:
    scale: 7500
    zoom_on: 'parca_polygon_lgd_peuplements'
    readonly: [parca_polygon_lgd_peuplements, parca_polygon_occup, ua_polygon_plt]
    groups:
      - name: LEGEND
        type: vector
        layers: ['parca_polygon_lgd_peuplements']
      - name: VECTEUR
        type: vector
        layers: &peuplements_w_vect ['com_line', 'com_point', 'infra_point_peuplements', 'infra_line', 'topo_line', 'infra_polygon', 'lieudit_point', 'road_line', 'road_polygon', 'route_line', 'route_polygon']
      - name: SEQUOIA
        type: vector
        layers: &peuplements_w_seq ['prop_line', 'pf_line', 'pf_polygon', 'sspf_polygon', 'sspf_polygon_plt', 'parca_polygon_occup', 'ua_polygon', 'ua_polygon_plt', 'ua_polygon_ame']
      - name: WMTS
        type: wmts
        layers: &peuplements_w_wmts ['wmts_scan25_grey', 'wmts_scan100', 'wmts_scan1000', 'wmts_pci', 'wmts_irc', 'wmts_rgb']

    themes:
      - name: 1_VECTEUR+SEQUOIA
        show: [*peuplements_w_vect, *peuplements_w_seq]
      - name: 2_VECTEUR+SEQUOIA+WMTS
        show: [*peuplements_w_vect, *peuplements_w_seq, *peuplements_w_wmts]
      - name: 3_SEQUOIA+WMTS
        show: [*peuplements_w_vect, *peuplements_w_wmts]

  layout:
    theme: '1_VECTEUR+SEQUOIA'
    legends:
      - name: legend1
        layers: ['parca_polygon_lgd_peuplements']
      - name: legend2
        layers: ['sspf_polygon_plt']

enjeux_environnementaux:
  canvas:
    scale: 15000
    zoom_on: 'parca_polygon_lgd_enjeux'
    readonly: [parca_polygon_lgd_enjeux]

    groups:
      - name : LEGEND
        type : vector
        layers : [parca_polygon_lgd_enjeux]
      - name : SEQUOIA
        type : vector
        layers : &enjeux_env_w_seq ['prop_line', 'pf_line', 'pf_polygon', 'pnr', 'znieff1', 'znieff2', 'zico', 'pn', 'sic', 'zps', 'ramsar', 'bios']
      - name : WMTS
        type : wmts
        layers : &enjeux_env_w_wmts ['wmts_scan25_grey']

    themes:
      - name: 1_SEQUOIA+WMTS
        show: [*enjeux_env_w_seq, *enjeux_env_w_wmts]

  layout:
    theme: '1_SEQUOIA+WMTS'
    legends:
      - name: legend1
        layers: ['parca_polygon_lgd_enjeux']
      - name: legend2
        layers: ['prop_line', 'pf_line', 'pf_polygon', 'pnr', 'znieff1', 'znieff2', 'zico', 'pn', 'sic', 'zps', 'ramsar', 'bios']

enjeux_sociaux:
  canvas:
    scale: 15000
    zoom_on: 'parca_polygon_lgd_enjeux'
    readonly: [parca_polygon_lgd_enjeux]
    groups:
      - name : LEGEND
        type : vector
        layers : [parca_polygon_lgd_enjeux]
      - name : SEQUOIA
        type : vector
        layers : &enjeux_sociaux_w_seq ['prop_line', 'pf_line', 'pf_polygon', 'ppi', 'ppr', 'ppe']
      - name : WMTS
        type : wmts
        layers : &enjeux_sociaux_w_wmts ['wmts_scan25_grey']

    themes:
      - name: 1_SEQUOIA+WMTS
        show: [*enjeux_sociaux_w_seq, *enjeux_sociaux_w_wmts]

  layout:
    theme: '1_SEQUOIA+WMTS'
    legends:
      - name: legend1
        layers: ['parca_polygon_lgd_enjeux']
      - name: legend2
        layers: ['ppi', 'ppr', 'ppe']

enjeux_patrimoniaux:
  canvas:
    scale: 15000
    zoom_on: 'parca_polygon_lgd_enjeux'
    readonly: [parca_polygon_lgd_enjeux]

    groups:
      - name : LEGEND
        type : vector
        layers : ['parca_polygon_lgd_enjeux']
      - name : SEQUOIA
        type : vector
        layers : &enjeux_pat_w_seq ['prop_line', 'pf_line', 'pf_polygon', 'mh', 'ppmh', 'site']
      - name : WMTS
        type : wmts
        layers : &enjeux_pat_w_wmts ['wmts_scan25_grey']
    themes:
      - name: 1_SEQUOIA+WMTS
        show: [*enjeux_pat_w_seq, *enjeux_pat_w_wmts]

  layout:
    theme: '1_SEQUOIA+WMTS'
    legends:
      - name: legend1
        layers: ['parca_polygon_lgd_enjeux']
      - name: legend2
        layers: ['mh', 'ppmh', 'site']

geologie:
  canvas:
    scale: 15000
    zoom_on: 'parca_polygon_lgd_enjeux'
    readonly: [parca_polygon_lgd_enjeux]

    groups:
      - name : LEGEND
        type : vector
        layers : ['parca_polygon_lgd_enjeux']
      - name : SEQUOIA
        type : vector
        layers : &geol_w_seq ['prop_line', 'pf_line', 'pf_polygon', 'geol']
      - name : WMTS
        type : wmts
        layers : &geol_w_wmts ['wmts_scan25_grey']
    themes:
      - name: 1_SEQUOIA+WMTS
        show: [*geol_w_seq, *geol_w_wmts]

  layout:
    theme: '1_SEQUOIA+WMTS'
    legends:
      - name: legend1
        layers: ['parca_polygon_lgd_enjeux']
      - name: legend2
        layers: ['geol']